version: '3.8.1'

services:
  app:
    build: .
    container_name: app_con # コンテナ名
    ports:
      - "8080:8000" # ローカルでは8080・コンテナ内では8000
    volumes:
      - ./src:/go/src
    tty: true # コンテナを起動したままにする